/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iss.gms.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;


public class LoadForm extends ActionForm {
	private FormFile file=null;
	//文件大小
	private String size;
	//文件名称
	private String filename;
	//插入表标示
	private String flag;
	public FormFile getFile() {
		return file;
	}
	public String getFlag() {
		return flag;
	}
	public void setFlag(String flag) {
		this.flag = flag;
	}
	public void setFile(FormFile file) {
		this.file = file;
	}
	public String getSize() {
		return size;
	}
	public void setSize(String size) {
		this.size = size;
	}
	public String getFilename() {
		return filename;
	}
	public void setFilename(String filename) {
		this.filename = filename;
	}


	
}