/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iss.gms.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;


public class TilesTestAction extends DispatchAction {

//	public static void main(String[] args) {
//		EmployeeDao dao = new EmployeeDao();
//		EmployeeBasicInfo ebi = new EmployeeBasicInfo();
//		ebi.setEmployeeId("12345");
//		try {
//			dao.addEmpInfo(ebi);
//		} catch (SQLException e) {
//			e.printStackTrace();
//		}
//	}
	
	

	public ActionForward toIndex(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("success");  
	}
	
}