/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.iss.gms.web.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.iss.gms.service.IUserService;
import com.iss.gms.service.UserServiceImpl;


public class UserAction extends DispatchAction {
	private static final Log log = LogFactory.getLog(UserAction.class);
	private UserServiceImpl userService;

	public UserServiceImpl getUserService() {
		return userService;
	}

	public void setUserService(UserServiceImpl userService) {
		this.userService = userService;
	}


	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			
			List lt =userService.queryAll();
			if(lt!=null){
				log.info("-----------------------------Í¨¹ý--------------------------");
				request.setAttribute("lt", lt);
			    return mapping.findForward("success");
			}else{
				return mapping.findForward("error");
			}
		} catch (SQLException e) {
			e.printStackTrace();
			log.error(e.getMessage());
			return mapping.findForward("error");
		}
		
	}
}